#!/usr/bin/env node
/**
 * Cool Tech People — Site Builder
 *
 * Reads every profile from /data/profiles/*.json and generates:
 *   - {slug}-profile.html for each person (from templates/profile.template.html)
 *   - profiles-data.js — ONE shared data file used by both index.html and directory.html
 *
 * To add a new profile: drop a new JSON file in /data/profiles/, add their
 * headshot to /images/, run `node build.js`, commit, push. That's it.
 */
const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data', 'profiles');
const OUT_DIR = path.join(__dirname, 'dist');
const TEMPLATE_PATH = path.join(__dirname, 'templates', 'profile.template.html');

function escapeHtml(str) {
  if (str === null || str === undefined) return '';
  return String(str);
}

function loadProfiles() {
  const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json'));
  return files.map(f => JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8')))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function renderExpertiseBlocks(expertise) {
  return Object.entries(expertise).map(([category, tags]) => `
      <div class="expertise-category">
        <div class="expertise-category-label">${escapeHtml(category)}</div>
        <div class="expertise-tag-group">
          ${tags.map(t => `<span class="expertise-tag">${escapeHtml(t)}</span>`).join('\n          ')}
        </div>
      </div>`).join('\n');
}

function renderProjectBlocks(projects) {
  return projects.map(p => `    <div class="project-item">
      <div class="project-title">${escapeHtml(p.title)}</div>
      <div class="project-desc">${escapeHtml(p.desc)}</div>
    </div>`).join('\n');
}

function renderContactBlocks(profile) {
  const c = profile.contact || {};
  const blocks = [];

  blocks.push(`    <div class="contact-item">
      <div class="contact-label">Email</div>
      <div class="contact-value">${c.email ? `<a href="mailto:${c.email}">${c.email}</a>` : '—'}</div>
    </div>`);

  if (c.website) {
    blocks.push(`    <div class="contact-item">
      <div class="contact-label">Website</div>
      <div class="contact-value">${c.website.startsWith('http') ? `<a href="${c.website}">${c.website.replace(/^https?:\/\//, '')}</a>` : c.website}</div>
    </div>`);
  }

  if (c.instagram) {
    const handle = c.instagram.replace(/\/$/, '').split('/').pop();
    blocks.push(`    <div class="contact-item">
      <div class="contact-label">Instagram</div>
      <div class="contact-value"><a href="${c.instagram}">@${handle}</a></div>
    </div>`);
  }

  if (c.linkedin) {
    const handle = c.linkedin === '#' ? null : c.linkedin.replace(/\/$/, '').split('/').pop();
    blocks.push(`    <div class="contact-item">
      <div class="contact-label">LinkedIn</div>
      <div class="contact-value"><a href="${c.linkedin}">${handle ? 'linkedin.com/in/' + handle : 'LinkedIn'}</a></div>
    </div>`);
  }

  blocks.push(`    <div class="contact-item">
      <div class="contact-label">Based In</div>
      <div class="contact-value">${escapeHtml(profile.locationOverride || profile.city)}</div>
    </div>`);

  if (profile.availableFor) {
    blocks.push(`    <div class="contact-item">
      <div class="contact-label">Available For</div>
      <div class="contact-value">${escapeHtml(profile.availableFor)}</div>
    </div>`);
  }

  if (profile.status) {
    blocks.push(`    <div class="contact-item">
      <div class="contact-label">Status</div>
      <div class="contact-value contact-status-box">${escapeHtml(profile.status)}</div>
    </div>`);
  }

  return blocks.join('\n');
}

function renderProfilePage(profile, template) {
  return template
    .replaceAll('{{NAME}}', escapeHtml(profile.name))
    .replaceAll('{{TITLE}}', escapeHtml(profile.title))
    .replaceAll('{{PHOTO}}', escapeHtml(profile.photo))
    .replaceAll('{{PHOTO_POSITION}}', escapeHtml(profile.photoPosition || 'center top'))
    .replaceAll('{{BIO}}', escapeHtml(profile.bio))
    .replaceAll('{{EXPERTISE_BLOCKS}}', renderExpertiseBlocks(profile.expertise))
    .replaceAll('{{PROJECT_BLOCKS}}', renderProjectBlocks(profile.projects))
    .replaceAll('{{CONTACT_BLOCKS}}', renderContactBlocks(profile));
}

function buildProfilesDataJs(profiles) {
  const records = profiles.map(p => ({
    name: p.name,
    title: p.title,
    city: p.city,
    regionLabel: p.regionLabel,
    location: p.region,
    category: p.categories.join(' '),
    role: p.roleTags.join(' '),
    expertise: Object.values(p.expertise).flat().map(t => t.toLowerCase().replace(/[^a-z0-9]+/g, '-')).join(' '),
    photo: p.photo,
    profile: `${p.slug}-profile.html`,
    position: p.photoPosition || 'center top',
    tags: p.cardTags || []
  }));

  return `// AUTO-GENERATED by build.js — do not edit by hand.
// Edit /data/profiles/*.json instead, then run \`node build.js\`.
const PROFILES = ${JSON.stringify(records, null, 2)};
if (typeof module !== 'undefined') module.exports = PROFILES;
`;
}

function copyStaticAssets() {
  const staticDir = path.join(__dirname, 'static');
  if (fs.existsSync(staticDir)) {
    fs.readdirSync(staticDir).forEach(file => {
      fs.copyFileSync(path.join(staticDir, file), path.join(OUT_DIR, file));
      console.log(`✓ copied ${file}`);
    });
  }
  fs.copyFileSync(path.join(__dirname, 'styles.css'), path.join(OUT_DIR, 'styles.css'));
  console.log('✓ copied styles.css');

  const imagesSrc = path.join(__dirname, 'images');
  const imagesOut = path.join(OUT_DIR, 'images');
  if (fs.existsSync(imagesSrc)) {
    if (!fs.existsSync(imagesOut)) fs.mkdirSync(imagesOut, { recursive: true });
    fs.readdirSync(imagesSrc).forEach(file => {
      if (file === '.gitkeep') return;
      fs.copyFileSync(path.join(imagesSrc, file), path.join(imagesOut, file));
    });
  }
}

function main() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const profiles = loadProfiles();
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');

  profiles.forEach(profile => {
    const html = renderProfilePage(profile, template);
    const outPath = path.join(OUT_DIR, `${profile.slug}-profile.html`);
    fs.writeFileSync(outPath, html);
    console.log(`✓ built ${profile.slug}-profile.html`);
  });

  const dataJs = buildProfilesDataJs(profiles);
  fs.writeFileSync(path.join(OUT_DIR, 'profiles-data.js'), dataJs);
  console.log(`✓ built profiles-data.js (${profiles.length} profiles)`);

  copyStaticAssets();

  console.log(`\nDone. ${profiles.length} profiles + full site built to /dist.`);
  console.log('This /dist folder is what you deploy.');
}

main();
